# This file was generated by GoReleaser. DO NOT EDIT.
class Tenki < Formula
  desc "Returns weather forecast in perticular prefecture."
  homepage "“https://github.com/mmmommm/tenki”"
  version "1.1.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mmmommm/tenki/releases/download/v1.1.9/tenki_1.1.9_Darwin_x86_64.tar.gz"
    sha256 "0aa0a3eef8bae853b3a6fbd65d7843c163242cf135e7b3c9487cf047f0b02778"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mmmommm/tenki/releases/download/v1.1.9/tenki_1.1.9_Linux_x86_64.tar.gz"
      sha256 "77d087e0e91a5aa7d8f50cfa6d0dd7c266859812f14f79513719a975ca8714f0"
    end
  end

  def install
    bin.install "tenki"
  end
end
